CXX = g++
CXXFLAGS = -g -Wall
TARGET = graph_program

$(TARGET): Graph.cpp
	$(CXX) $(CXXFLAGS) Graph.cpp -o $(TARGET)

clean:
	rm -f $(TARGET)' > Level3/Makefile

#how to run:
#cd Level3
#make
#./graph_program -v (vertex number) -e (edge number) -s (number of seed)
